FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY module_11/ ./module_11/

CMD ["uvicorn", "module_11.gateway.main:app", "--host", "0.0.0.0", "--port", "8080"]