FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY module_4/ ./module_4/

CMD ["celery", "-A", "module_4.app_celery.new_app_celery", "worker", "--loglevel=info"]
