# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x05\x62ooks\"/\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x0fGetBookResponse\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book2G\n\x0b\x42ookService\x12\x38\n\x07GetBook\x12\x15.books.GetBookRequest\x1a\x16.books.GetBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=21
  _globals['_BOOK']._serialized_end=68
  _globals['_GETBOOKREQUEST']._serialized_start=70
  _globals['_GETBOOKREQUEST']._serialized_end=98
  _globals['_GETBOOKRESPONSE']._serialized_start=100
  _globals['_GETBOOKRESPONSE']._serialized_end=144
  _globals['_BOOKSERVICE']._serialized_start=146
  _globals['_BOOKSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
