apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-configmap
data:
  DATABASE_URL: "postgresql+asyncpg://techcore:techcore@postgresql-service:5432/techcore"
  POSTGRES_SERVER: "postgresql-service"
  PYTHONPATH: "/app"