"""Second migrate

Revision ID: 1c0d51d6d5c0
Revises: 062ee21d8fe3
Create Date: 2025-11-05 14:08:20.116368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0d51d6d5c0'
down_revision: Union[str, None] = '062ee21d8fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
