"""delete Relationship

Revision ID: 32ef67f934f0
Revises: bd044e8a5f97
Create Date: 2025-11-07 21:16:43.818924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ef67f934f0'
down_revision: Union[str, None] = 'bd044e8a5f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_author_id_fkey'), 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('book_author_id_fkey'), 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###
