"""Relationship

Revision ID: bd044e8a5f97
Revises: 1c0d51d6d5c0
Create Date: 2025-11-05 14:10:30.864794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd044e8a5f97'
down_revision: Union[str, None] = '1c0d51d6d5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###
